.TH maildir2qmtp 1
.SH NAME
maildir2qmtp \- blast a maildir across QMTP
.SH SYNOPSIS
.B maildir2smtp
.I dir
.I prefix
.I targetip
.SH DESCRIPTION
.B maildir2qmtp
is just like
.B maildir2smtp
except that
(1) it uses QMTP instead of SMTP
and
(2) it does not take a
.I helohost
argument.

.B maildir2qmtp
is faster than
.BR maildir2smtp .
.SH "SEE ALSO"
maildir2smtp(1),
qmail-qmtpd(8)
