.TH qmail-lspawn 8
.SH NAME
qmail-lspawn \- schedule local deliveries
.SH SYNOPSIS
.B qmail-lspawn
.SH DESCRIPTION
.B qmail-lspawn
reads a series of local delivery commands from descriptor 0,
invokes
.B qmail-alias
to perform the deliveries,
and prints the results to descriptor 1.

.B qmail-lspawn
invokes
.B qmail-alias
asynchronously,
so the results may not be in the same order as the commands.

For each recipient address,
.B qmail-lspawn
first checks the
.B qmail-users
mechanism, and then
invokes
.B qmail-getpw
if necessary,
to find out which local user controls that address.
.B qmail-lspawn
runs
.B qmail-alias
under the user's uid and gid.
It does not set up any supplementary groups.

.B qmail-lspawn
treats an empty mailbox name as a trash address.
.SH "SEE ALSO"
envelopes(5),
qmail-users(5),
qmail-getpw(8),
qmail-send(8),
qmail-alias(8)
